plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: shell
    css_class   : 'highlight' ## see https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers
    

collections:
  manual:
    output: true
  posts:
    output: true
  appnotes:
    output: true
  book:
    output: true
  qs:
    output: true
  services:
    output: true    
  trains:
    output: true
  doc:
    output: true
  tutorial_base:
    output: true
  tutorial_rsa:
    output: true
  tutorial_iot:
    output: true
  tutorial_eval:
    output: true
  tutorial_maven:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: Bndtools.org
      image: /images/swirl-128.png

title: Bndtools

logo: /images/swirl-128.png


exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - '.gitignore'
  - '.github'
  - '.project'
  - '*.sh'
  - '/vendor'
  - 'pagefind'


