plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown

collections:
  manual:
    output: true
  posts:
    output: true
  appnotes:
    output: true
  book:
    output: true
  services:
    output: true    
  trains:
    output: true
  doc:
    output: true
  tutorial_base:
    output: true
  tutorial_rsa:
    output: true
  tutorial_iot:
    output: true
  tutorial_wrap:
    output: true
  tutorial_maven:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: Bndtools.org
      image: /images/swirl-128.png

title: Bndtools

logo: /images/swirl-128.png


exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - '.gitignore'
  - '.github'
  - '.project'
  - 'run.sh'
  - '/vendor'

